# Generated by Django 3.1 on 2021-01-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
