# Generated by Django 3.1 on 2021-01-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210108_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(default='', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', editable=False, max_length=70),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', editable=False, max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(editable=False, max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(editable=False, max_length=90),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
